# Regression with Decision Trees

In [1]:
import numpy as np

# Generate synthetic data for testing Decision Tree Regression
np.random.seed(42)  # For reproducibility
X = np.random.rand(100, 5)  # 100 samples, 5 features
y = 3 * X[:, 0] + 2 * X[:, 1] - X[:, 2] + np.random.randn(100) * 0.1  # Target variable

# Print the first few rows of data to verify
print("Feature matrix (X):")
print(X[:5])
print("\nTarget variable (y):")
print(y[:5])

Feature matrix (X):
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Target variable (y):
[ 2.32723063 -0.09440828  1.26417293  0.57625122  1.73256029]


In [2]:
from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(max_depth=2)
tree_reg.fit(X, y)

DecisionTreeRegressor(max_depth=2)

- DecisionTreeRegressor results in a similar tree as the classification model.
- The main difference is that instead of predicting a class in each node, it predicts a value.
- It traverses the tree, eventually reaches a leaf node, and then predicts the average target value of all the training instances associated with that leaf node.
- **CART cost function for regression**: $$ J(k, t_k) = \frac{m_{\text{left}}}{m}\text{MSE}_{\text{left}} + \frac{m_{\text{right}}}{m}\text{MSE}_{\text{right}} $$

where $$ \begin{cases}
\text{MSE}_{\text{node}} = \sum_{i \in \text{node}} (\hat{y}_{\text{node}} - y^{(i)})^2 \\
\hat{y}_{\text{node}} = \frac{1}{m_{\text{node}}} \sum_{i \in \text{node}} y^{(i)}
\end{cases}$$

Just like classification, these models are prone to overfitting without regularization in regression as well. 

## Limitations

- Decision Trees make perpendicular decision boundaries, which makes them sensitive to training set roatation.
- Decision Trees are very sensitive to small variations in the training data. 